export const ORDERBOOK_ENDPOINT = "/api/orderbook";

export const ORDERBOOK_DEFAULT_BASE_PRICE = 100000;
export const ORDERBOOK_DEFAULT_DEPTH = 8;
export const ORDERBOOK_UPDATE_INTERVAL_MS = 1000;
export const ORDERBOOK_LIST_STALE_TIME_MS = 30000;
export const ORDERBOOK_TIMELINE_MAX_POINTS = 24;

export const ORDERBOOK_MIN_QUANTITY = 1;
export const ORDERBOOK_MAX_QUANTITY = 12;
export const ORDERBOOK_PRICE_TICK = 100;
export const ORDERBOOK_PRICE_SWING_STEP = 2;
